module.exports = {
    BasicDialog: require('@tractorzoom/basic-dialog'),
    Button: require('@tractorzoom/button'),
    ButtonDropdown: require('@tractorzoom/button-dropdown'),
    ButtonGroup: require('@tractorzoom/button-group'),
    Chip: require('@tractorzoom/chip'),
    EquipmentCard: require('@tractorzoom/equipment-card'),
    List: require('@tractorzoom/list'),
    NativeSelect: require('@tractorzoom/native-select'),
    NumberField: require('@tractorzoom/number-field'),
    Lozenge: require('@tractorzoom/lozenge'),
    PlacesSelect: require('@tractorzoom/places-select'),
    Radio: require('@tractorzoom/radio'),
    Select: require('@tractorzoom/select'),
    SidePanel: require('@tractorzoom/side-panel'),
    SimpleSelect: require('@tractorzoom/simple-select'),
    TextField: require('@tractorzoom/text-field'),
    Theme: require('@tractorzoom/theme'),
    UsageMeter: require('@tractorzoom/usage-meter'),
};
