name: publish

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - name: Lerna Bootstrap
              run: ./node_modules/.bin/lerna bootstrap
            - run: npm test

    npm-publish:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: git config --global user.email "dev-support@tractorzoom.com"
            - run: git config --global user.name "Tractor Zoom"
            - run: npm ci
            - name: Lerna Bootstrap
              run: ./node_modules/.bin/lerna bootstrap
            - name: Authenticate with NPM Registry
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            - name: Lerna Publish
              run: ./node_modules/.bin/lerna publish --create-release github --yes
              env:
                  GH_TOKEN: ${{ github.token }}

    # publish-github-pages:
    #     needs: npm-publish
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-node@v1
    #           with:
    #               node-version: 12
    #         - run: npm ci
    #         - name: Lerna Bootstrap
    #           uses: m19c/action-lerna@master
    #           with:
    #               args: 'bootstrap'
    #         - run: npm run build-storybook
    #         - name: 'Deploy to GitHub Pages'
    #           uses: crazy-max/ghaction-github-pages@v1
    #           with:
    #               target_branch: gh-pages
    #               build_dir: storybook-static
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
